// react-web/src/components/Landing/categories/Categories.tsx
import { FC } from "react";
import { List } from "immutable";

import Category from "../../../models/Category";

interface CategoriesProps {
  categories: List<Category>;
}

const Categories: FC<CategoriesProps> = ({ categories }) => {
  return (
    <div className="container my-5">
      <div className="d-block text-center mb-5">
        <h3>Shop by category</h3>
        <a
          className="text-dark font-weight-bold"
          href="https://demos.creative-tim.com/astro-ecommerce/landing/#"
        >
          Browse all categories &gt;
        </a>
      </div>
      <div className="row mb-5">
        {categories.map((category) => (
          <div className="col-md-6 col-lg-3">
            <a href="https://demos.creative-tim.com/astro-ecommerce/landing/#"></a>
            <div className="card card-background align-items-start mb-4 mb-lg-0 undefined">
              <a href="https://demos.creative-tim.com/astro-ecommerce/landing/#">
                <div
                  className="full-background"
                  style={{
                    backgroundImage: `url(${require("../images/category1.jpg")})`,
                    backgroundSize: "cover",
                  }}
                ></div>
              </a>
              <div className="card-body text-center w-100 pt-8">
                <a href="https://demos.creative-tim.com/astro-ecommerce/landing/#"></a>
                <div className="d-block mt-10">
                  <a href="https://demos.creative-tim.com/astro-ecommerce/landing/#">
                    <p className="text-white font-weight-bold mb-1">
                      {category.editionName}
                    </p>
                    <h4 className="text-white font-weight-bolder">
                      {category.name}
                    </h4>
                  </a>
                  <a
                    href="https://demos.creative-tim.com/astro-ecommerce/landing/#"
                    className="text-white text-sm font-weight-semibold mb-0"
                  >
                    See products &gt;
                  </a>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Categories;

// frontend/src/app/landing-page/categories/categories.component.ts
import { Component, Input } from '@angular/core';
import { UtilitiesService } from '../../shared/utilities.service';

@Component({
  selector: 'app-categories',
  templateUrl: './categories.component.html',
  styleUrls: ['./categories.component.css']
})
export class CategoriesComponent {
  @Input() categories: any;

  constructor(private utilitiesService: UtilitiesService) { }

  generateSlug(categoryName: string) {
    const slug = this.utilitiesService.createSlug(categoryName);
    return slug
  }
}
<div class="row mb-5">

    <div *ngFor="let category of categories" class="col-md-6 col-lg-3">
        <a href="https://demos.creative-tim.com/astro-ecommerce/landing/#"></a>
        <div class="card card-background align-items-start mb-4 mb-lg-0 undefined"><a
                href="https://demos.creative-tim.com/astro-ecommerce/landing/#">
                <div class="full-background"
                    style="background-image:url(assets/categories/{{ generateSlug(category.name) }}.jpg);background-size:cover">
                </div>
            </a>
            <div class="card-body text-center w-100 pt-8"><a
                    href="https://demos.creative-tim.com/astro-ecommerce/landing/#"></a>
                <div class="d-block mt-10"><a href="https://demos.creative-tim.com/astro-ecommerce/landing/#">
                        <p class="text-white font-weight-bold mb-1">{{ category.editionName }}</p>
                        <h4 class="text-white font-weight-bolder">{{ category.name }}</h4>
                    </a><a href="https://demos.creative-tim.com/astro-ecommerce/landing/#"
                        class="text-white text-sm font-weight-semibold mb-0">See products &gt;</a></div>
            </div>
        </div>
    </div>
    
</div>
